# Generated by Django 3.0.6 on 2020-05-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               related_name='currency', to='scrapper.Currency')),
                ('main_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='main_currency',
                                                    to='scrapper.Currency')),
            ],
        ),
    ]
